spring:
  #配置数据库数据源
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/cquptacademic?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: 123456
      max-active: 20
      max-wait: 5000
      initial-size: 1
      filters: stat,log4j,wall
      validation-query: SELECT 'X'   #验证连接
      enable: true
      #监控配置
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: 123456
        url-pattern: /druid/*
  #配置servlet
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  #thymeleaf的配置
  thymeleaf:
    cache: false
    enabled: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#配置mybatisplus映射
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  global-config:
    db-config:

      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


mybatis:
  configuration:
    map-underscore-to-camel-case: true

##pagehelper分页插件配置(写sql时不用写limit)
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql

#配置log日志的存储路径
logging:
  level:
    root: info
    com.lrm: debug
  file:
    name: log/Log.log

#端口号为8080
server:
  port: 8080


#评论时默认头像
comment.avatar: /images/cquptLOGO.jpg